name: Generate UML Diagrams

on:
  push:
    paths:
      - '**/*.puml'
  pull_request:
    paths:
      - '**/*.puml'

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenJDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Install PlantUML
        run: sudo apt-get install plantuml

      - name: Generate UML diagrams from .puml files
        run: |
          for file in $(find . -name "*.puml"); do
            echo "Generating diagram for $file"
            plantuml $file
            echo "Generated diagram for $file"
          done

      - name: Check git status before push
        run: git status

      - name: Commit and push generated diagrams
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add '*.png' || echo "No .png files to add"
          git commit -m "Generate UML diagrams" || echo "No changes to commit"
          git push || echo "Push failed"
